<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lisda Holilah">
<meta name="dcterms.date" content="2024-01-04">

<title>Pengaruh Ekspor CPO ke India Sebagai Pasar Utama terhadap PDB Indonesia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-8a79a254b8e706d3c925cde0a310d4f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Ekspor CPO ke India Sebagai Pasar Utama terhadap PDB Indonesia</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lisda Holilah </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 4, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Minyak Sawit atau Crude Palm Oil (CPO) merupakan salah satu komoditas ekspor terbesar di Indonesia. CPO memiliki peran yang sangat penting terhadap distribusi perekonomian negara. Perdagangan Internasional sendiri merupakan salah satu kegiatan yang membantu berjalannnya sebuah kegiatan ekspor maupun impor. Indonesia sendiri telah melakukan kegiatan tersebut hingga bergabung dengan berbagai organisasi perdagangan dunia. Banyak sekali tantangan yang harus dihadapi dalam melakukan perdagangan internasional. Seperti regulasi, konflik atau kondisi negara tersebut hingga pertumbuhan ekonomi yang mempengaruhi mata uang yang digunakan.</p>
<p>Salah satu komoditas andalan ekspor Indonesia yaitu CPO yang berperan penting bagi negara. Penerimaan devisa negara dari CPO mencapai 80% pertahun dari total nilai ekspor komoditas pertanian yang menjadi andalan di Indonesia seperti CPO, kopi, teh, tuna, serta kakao (Prasetyo dkk., 2018). Perkembangan dunia yang cepat ini yang menyebabkan peningkatan kebutuhan barang dan jasa. Hal tersebut mendorong terjadinya transaksi internasional yang dapat terjadi apabila suatu negara memiliki surplus produksi dalam negeri dan kemudian mengekspor produk tersebut ke negara lain. Perdagangan internasional ini berpengaruh terhadap pertumbuhan produk domestik bruto (PDB) suatu negara.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Berdasarkan data ekspor yang didapatkan dari Badan Pusat Statistik India merupakan negara tujuan Ekspor terbesar di Indonesia, disusul Tiongkok dan Pakistan setelahnya. Dalam penelitian ini penulis menggunakan data yang bersifat time series yaitu tahun 2017-2023. Pertumbuhan ekonomi yang sebagaimana diukur oleh GDP, selalu menjadi indikator makroekonomi yang populer dan merupakan hal yang sangat penting bagi pembuatan kebijakan (Ge dan Tang, 2020). Teori ekonomi makro juga menyebutkan bahwa hubungan antara ekspor dengan pendapatan nasional merupakan suatu persamaan identitas karena ekspor merupakan bagian dari pendapatan (santoso, 2021)</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Apakah Ekspor CPO di Pasar Utama memiliki pengaruh terhadap PDB Indonesia?</li>
<li>Bagaimana jika Indonesia tidak melakukan ekspor CPO ke India?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Bagian ini merupakan jawaban yang akan dicapai dari pembahasan laporan, biasanya dirumuskan dari poin-poin masalah yang telah dijabarkan sebelumnya. Identifikasi siapa saja stakeholders yang dapat memanfaatkan penelitian ini.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl) </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data metopel.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>• Perdagangan Internasional</p>
<p>Perdagangan internasional sendiri merupakan kegiatan jual beli yang dilakukan dalam kancah dunia atau perdagangan antar negara. Perdagangan Internasional adalah kegiatan memperdagangkan barang dan jasa yang dilakukan oleh penduduk suatu negara dengan penduduk negara lain. Perdagangan Internasional tidak hanya mencakup ekpor impor barang tetapi juga jasa. Pedagangan internasional diciptakan agar memudahkan suatu negara untuk memenuhi kebutuhan yang tidak ada atau kurang di negara nya. Selain itu, perdagangan internasional diharapkan dapat menjalin hubungan erat antar negara saat bekerja sama. Manfaat lainnya yaitu menaikan pendapatan negara, investasi hingga lapangan pekerjaan. Perdagangan internasional cukup memiliki dampak yang luas bagi perekonomian suatu negara.</p>
<p>• CPO</p>
<p>Minyak sawit atau CPO termasuk kedalam salah satu minyak yang berkontribusi besar di dunia. CPO memiliki banyak manfaat dibidang Kesehatan, pangan hingga bahan baku. Indonesia sendiri merupakan negara penghasil CPO terbesar di dunia, diikuti Malaysia dan Thailand setelahnya. Hal ini disebabkan oleh luasnya perkebunan sawit di Indonesia yang mencapai 14,68 juta hektar pada tahun 2019 dan dapat menghasilkan 43 juta ton pertahun. India sendiri merupakan pengimpor CPO terbesar di dunia pada tahun 2020 dengan presentase 42% atau senilai dengan US$ 4,9 Miliar menurut ITC. Indonesia menjadi salah satu negara pengekspor CPO ke India dan berdasarkan data dari badan pusat statistik, India menjadi urutan pertama sebagai negara yang mengimpor paling banyak di Indonesia.</p>
<p>• Ekspor</p>
<p>Ekspor dan Impor merupakan bagian dari perdagangan internasional. Ekspor sendiri memiliki banyak pengertian. Salah satunya adalah mengeluarkan barang atau jasa dari daerah pabean ke luar daerah pabean, dalam artian tersebut menjual barang ke luar negeri bukan saja arti dari ekspor. Tetapi mengirim barang entah diperjual belikan atau tidak, tetap disebut ekspor. Kegiatan tersebut tentu sangat berpengaruh terhadap pendapatan negara atau PDB. Apabila ekspor mengalami peningkatan maka produksi barang dan jasa juga mengalami peningkatan karena adanya permintaan. Begitu juga sebaliknya, jika ekspor mengalami penurunan karena permintaan barang dan jasa dapat menyebabkan angka impor yang lebih besar dibanding ekspor dan hal tersebut dapat menurunkan pertumbuhan ekonomi.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut adalah data yang digunakan sebagai objek penelitian yaitu Jumlah/Ton, nilai FOB dan PDB Indonesia:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>tahun</strong></th>
<th><strong>India/ton (X)</strong></th>
<th><strong>Nilai FOB (S)</strong></th>
<th><strong>PDB(Y)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2017</td>
<td>7376.8</td>
<td>4967.1</td>
<td>9.912.928</td>
</tr>
<tr class="even">
<td>2018</td>
<td>6415.8</td>
<td>3626.0</td>
<td>10.425.852</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>4655.3</td>
<td>2303.5</td>
<td>10.949.155</td>
</tr>
<tr class="even">
<td>2020</td>
<td>4631.9</td>
<td>3038.6</td>
<td>10.722.999</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>3101.8</td>
<td>3356.4</td>
<td>11.120.060</td>
</tr>
<tr class="even">
<td>2022</td>
<td>4999.3</td>
<td>5324.8</td>
<td>11.710.248</td>
</tr>
<tr class="odd">
<td>2023</td>
<td>5406.9</td>
<td>4521.2</td>
<td>123.01.394</td>
</tr>
</tbody>
</table>
<p>penelitian ini menggunakan data berbentuk <em>time series</em> dari tahun 2017-2023</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'C:/Users/LISDA/Documents/metopel tugas'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl) </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>reg2<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>dat,Y<span class="sc">~</span>X<span class="sc">+</span>S)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X + S, data = dat)

Residuals:
      1       2       3       4       5       6       7 
-642883    5111  320505 -210563 -583190   13117 1097903 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 11657572.4  1295923.6   8.996 0.000845 ***
X               -419.7      245.9  -1.707 0.163050    
S                401.4      308.0   1.303 0.262394    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 725600 on 4 degrees of freedom
Multiple R-squared:  0.4458,    Adjusted R-squared:  0.1687 
F-statistic: 1.609 on 2 and 4 DF,  p-value: 0.3071</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg2)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>Y,dat<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Jumlah/ton"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="plot%20jumlah.png" class="img-fluid figure-img"></p>
<figcaption>Plot eror terhadap jumah ekspor</figcaption>
</figure>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg2)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X,dat<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"PDB"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="plot%20pdb.png" class="img-fluid figure-img"></p>
<figcaption>Plot eror terhadap PDB</figcaption>
</figure>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode analisis yang digunakan dalam analisis ini adalah deskriptif kuantitif. Cara mencarinya sendiri dengan menggunakan regresi multivariat dimana:</p>
<p><span class="math inline">\(y=\beta_0 + \beta_1 x+\beta_2{s}+\mu\)</span></p>
<p>cara tersebut bertujuan untuk mencari hubungan antara X dan S terhadap Y. Di mana X, S, Y disini adalah jumlah/ton, nilai FOB, dan PDB Indonesia.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 28%">
<col style="width: 20%">
<col style="width: 17%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Aspek</strong></th>
<th><strong>Koefisien / Nilai</strong></th>
<th><strong>Std. Error</strong></th>
<th><strong>t-value</strong></th>
<th><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Residuals</strong></td>
<td>-642883, 5111, 320505, -210563, -583190, 13117, 1097903</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td><strong>Intercept</strong></td>
<td>11,657,572.4</td>
<td>1,295,923.6</td>
<td>8.996</td>
<td>0.000845</td>
</tr>
<tr class="odd">
<td><strong>X (Jumlah Ekspor CPO ke India)</strong></td>
<td>-419.7</td>
<td>245.9</td>
<td>-1.707</td>
<td>0.163050</td>
</tr>
<tr class="even">
<td><strong>S (PDB Indonesia)</strong></td>
<td>401.4</td>
<td>308.0</td>
<td>1.303</td>
<td>0.262394</td>
</tr>
<tr class="odd">
<td><strong>Residual Standard Error</strong></td>
<td>725,600</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td><strong>Multiple R-squared</strong></td>
<td>0.4458</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="odd">
<td><strong>Adjusted R-squared</strong></td>
<td>0.1687</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td><strong>F-statistic</strong></td>
<td>1.609</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>Koefisien untuk X adalah -419.7, yang berarti bahwa setiap kenaikan satu ton ekspor CPO ke India dapat menyebabkan penurunan PDB Indonesia sebesar 419.7. Namun, p-value untuk koefisien ini adalah 0.163050, yang lebih besar dari 0.05, yang menunjukkan bahwa jumlah ekspor CPO ke India tidak signifikan dalam mempengaruhi PDB Indonesia. Artinya, meskipun ada hubungan negatif antara ekspor CPO dan PDB, hubungan ini tidak cukup kuat atau signifikan dalam model ini. Untuk S sendiri adalah 401.4, yang menunjukkan bahwa setiap kenaikan satu unit nilai FOB akan meningkatkan PDB Indonesia sebesar 401.4. Meskipun ada hubungan positif antara nilai FOB dan PDB, p-value untuk koefisien ini adalah 0.262394, yang lebih besar dari 0.05, sehingga nilai FOB tidak signifikan dalam mempengaruhi PDB Indonesia dalam model ini. Dengan kata lain, meskipun ada efek positif yang diindikasikan oleh koefisien, hubungan ini tidak cukup kuat untuk dianggap signifikan dalam mempengaruhi PDB.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>reg2<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>dat,Y<span class="sc">~</span>X<span class="sc">+</span>S)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X + S, data = dat)

Residuals:
      1       2       3       4       5       6       7 
-642883    5111  320505 -210563 -583190   13117 1097903 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 11657572.4  1295923.6   8.996 0.000845 ***
X               -419.7      245.9  -1.707 0.163050    
S                401.4      308.0   1.303 0.262394    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 725600 on 4 degrees of freedom
Multiple R-squared:  0.4458,    Adjusted R-squared:  0.1687 
F-statistic: 1.609 on 2 and 4 DF,  p-value: 0.3071</code></pre>
</div>
</div>
<p>Call: lm(formula = Y ~ X + S, data = dat)</p>
<p>Residuals: 1 2 3 4 5 6 7 -642883 5111 320505 -210563 -583190 13117 1097903</p>
<p>Coefficients: Estimate Std. Error t value Pr(&gt;|t|)<br>
(Intercept) 11657572.4 1295923.6 8.996 0.000845 *** X -419.7 245.9 -1.707 0.163050<br>
S 401.4 308.0 1.303 0.262394</p>
<hr>
<p>Signif. codes: 0 ‘<em><strong>’ 0.001 ‘</strong>’ 0.01 ‘</em>’ 0.05 ‘.’ 0.1 ‘ ’ 1</p>
<p>Residual standard error: 725600 on 4 degrees of freedom Multiple R-squared: 0.4458, Adjusted R-squared: 0.1687 F-statistic: 1.609 on 2 and 4 DF, p-value: 0.3071</p>
<p>Setiap kenaikan nilai FOB diasumsikan nilainya 1, maka dapat meningkatkan PDB sebesar 401.4, tetapi jumlah Ekspor berpengaruh negatif pada PDB Indonesia, jika diasumsikan jumlah ekspor/ton 1 maka PDB akan ada penurunan -419.7</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Dapat diketahui bahwa setiap kenaikan nilai menunjukkan pengaruh positif terhadap PDB Indonesia, kenaikan nilai FOB atau harga jual CPO tersebut memiliki dampak positif terhadap perekonomian Indonesia. Dengan kata lain, jika harga CPO naik di pasar India, maka akan berkontribusi pada peningkatan PDB Indonesia. Namun di sisi lain, jumlah ekspor CPO yang meningkat 1 ton berpengaruh negatif terhadap PDB Indonesia, dengan nilai penurunan sebesar -419.7. Hal ini dapat disebabkan oleh faktor-faktor seperti peningkatan biaya produksi atau faktor lain yang mungkin terkait dengan skala ekspor yang lebih tinggi, yang justru berpotensi menurunkan pendapatan sektor tersebut. Meskipun volume ekspor yang lebih tinggi dapat memberikan kontribusi negatif terhadap PDB Indonesia, jika nilai FOB atau harga CPO tetap tinggi, pengaruh positif dari kenaikan nilai FOB diharapkan lebih dominan kedepannya. Dengan demikian, faktor harga atau nilai jual CPO yang tinggi itulah yang lebih memengaruhi positif terhadap PDB Indonesia dibandingkan dengan sekadar peningkatan volume ekspor. Dengan kata lain, hal ekspor CPO memiliki pengaruh meskipun tidak terlalu signifikan dan kondisi tersebut bisa berubah kapanpun. Adapun ekspor cpo ke pasar utama menjadi salah satu dari banyak nya faktor yang mempengaruhi PDB Indonesia</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Abisag Indah Itamary, I. M. (2022). ANALISIS DAYA SAING EKSPOR CRUDE PALM OIL (CPO) INDONESIA DI PASAR INDIA. Jurnal Ekonomi Pembangunan, 208-217.</p>
<p>Badan Pusat Statistik. (2025, 1 4). Retrieved from https://www.bps.go.id/id</p>
<p>Fajar Santoso, B. A. (2021). PENGARUH EKSPOR TERHADAP GROSS DOMESTIC PRODUCT . JEMES – Jurnal Ekonomi Manajaemen dan Sosial.</p>
<p>Ge, Yiqing, dan Tang, Ke. (2020). Commodity process and GDP growth. International Review of Financial Analysis. https://doi.org/10.1016/j.irfa.2020.10 1512</p>
<p>https://js.bsn.go.id/index.php/standardisasi/article/view/51/39. (2012). KAJIAN MUTU DAN KARAKTERISTIK MINYAK SAWIT INDONESIA SERTA PRODUK FRAKSINYA. Jurnal Standardisasi , 13-21.</p>
<p>Indana Zulfa Ningtias, A. B. (2022). Analisis Faktor-Faktor Yang Mempengaruhi Ekspor Cpo Indonesia Ke India. https://jurnal.peneliti.net/index.php/JIWP, 213-225.</p>
<p>International Trade Administration. (n.d.). Retrieved from trade.gov: https://www-trade-gov.translate.goog/country-commercial-guides/malaysia-agricultural-sector?_x_tr_sl=en&amp;_x_tr_tl=id&amp;_x_tr_hl=id&amp;_x_tr_pto=sge#:~:text=Malaysia%20merupakan%20produsen%20dan%20eksportir,ekspor%20dunia%20pada%20tahun%202020.</p>
<p>Laili Monita Wulandari, S. Z. (2019). PENGARUH PERDAGANGAN INTERNASIONAL DAN INVESTASI TERHADAP PERTUMBUHAN EKONOMI INDONESIA PADA TAHUN 2007-2017. Jurnal REP (Riset Ekonomi Pembangunan), 119-127.</p>
<p>Prasetyo, A., Marwanti, S., &amp; Darsono, N. (2018). Keunggulan Komparatif dan Kinerja Ekspor Minyak Sawit Mentah Indonesia di Pasar Internasional. Jurnal Agro Ekonomi, 35(2), 89. https://doi.org/10.21082/jae.v35n2.2017.89-103</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>